### ISSUE TITLE
Débloquer niveau en fonctions des joueurs

### ISSUE THREAD

**Issue by raphaelsty** [raphaelsty/sidsimon#50]

**Comment by noemieDeloeuvre** [comment]
Y'a des problèmes. Joueur id 2 : aucun niveau n'apparait (alors qui'il a joué à des parties puisqu'il apparait dans mouvement_joueur)
Joueur id 1 : tous les niveaux apparaissent (alors qu'il a joué que jusqu'au niveau 33)
